["Widow Queen"]
id = 1
clientid = 368
speed = 20
premium = true

["Racing Bird"]
id = 2
clientid = 369
speed = 20
premium = true

["War Bear"]
id = 3
clientid = 370
speed = 20
premium = true

["Black Sheep"]
id = 4
clientid = 371
speed = 20
premium = true

["Midnight Panther"]
id = 5
clientid = 372
speed = 20
premium = true

[Draptor]
id = 6
clientid = 373
speed = 20
premium = true

[Titanica]
id = 7
clientid = 374
speed = 20
premium = true

["Tin Lizzard"]
id = 8
clientid = 375
speed = 20
premium = true

[Blazebringer]
id = 9
clientid = 376
speed = 20
premium = true

["Rapid Boar"]
id = 10
clientid = 377
speed = 20
premium = true

[Stampor]
id = 11
clientid = 378
speed = 20
premium = true

["Undead Cavebear"]
id = 12
clientid = 379
speed = 20
premium = true

[Donkey]
id = 13
clientid = 387
speed = 20
premium = true

["Tiger Slug"]
id = 14
clientid = 388
speed = 20
premium = true

[Uniwheel]
id = 15
clientid = 389
speed = 20
premium = true

["Crystal Wolf"]
id = 16
clientid = 390
speed = 20
premium = true

["War Horse"]
id = 17
clientid = 392
speed = 20
premium = true

["Kingly Deer"]
id = 18
clientid = 401
speed = 20
premium = true

["Tamed Panda"]
id = 19
clientid = 402
speed = 20
premium = true

[Dromedary]
id = 20
clientid = 405
speed = 20
premium = true

["Scorpion King"]
id = 21
clientid = 406
speed = 20
premium = true

["Rented Horse"]
id = 26
clientid = 438
speed = 20
premium = false

["Armoured War Horse"]
id = 23
clientid = 426
speed = 20
premium = false

["Shadow Draptor"]
id = 24
clientid = 427
speed = 20
premium = true

["Lady Bug"]
id = 27
clientid = 447
speed = 20
premium = true

["Manta Ray"]
id = 28
clientid = 450
speed = 20
premium = true

[Ironblight]
id = 29
clientid = 502
speed = 20
premium = true

["Magma Crawler"]
id = 30
clientid = 503
speed = 20
premium = true

[Dragonling]
id = 31
clientid = 506
speed = 20
premium = true

[Gnarlhound]
id = 32
clientid = 515
speed = 20
premium = true

["Crimson Ray"]
id = 33
clientid = 521
speed = 20
premium = false

[Steelbeak]
id = 34
clientid = 522
speed = 20
premium = false

["Water Buffalo"]
id = 35
clientid = 526
speed = 20
premium = true

[Tombstinger]
id = 36
clientid = 546
speed = 20
premium = false

[Platesaurian]
id = 37
clientid = 547
speed = 20
premium = false

[Ursagrodon]
id = 38
clientid = 548
speed = 20
premium = true

["The Hellgrip"]
id = 39
clientid = 559
speed = 20
premium = true

["Noble Lion"]
id = 40
clientid = 571
speed = 20
premium = true

["Desert King"]
id = 41
clientid = 572
speed = 20
premium = false

["Shock Head"]
id = 42
clientid = 580
speed = 20
premium = true

[Walker]
id = 43
clientid = 606
speed = 20
premium = true

[Azudocus]
id = 44
clientid = 621
speed = 20
premium = false

[Carpacosaurus]
id = 45
clientid = 622
speed = 20
premium = false

["Death Crawler"]
id = 46
clientid = 624
speed = 20
premium = false

[Flamesteed]
id = 47
clientid = 626
speed = 20
premium = false

["Jade Lion"]
id = 48
clientid = 627
speed = 20
premium = false

["Jade Pincer"]
id = 49
clientid = 628
speed = 20
premium = false

[Nethersteed]
id = 50
clientid = 629
speed = 20
premium = false

[Tempest]
id = 51
clientid = 630
speed = 20
premium = false

["Winter King"]
id = 52
clientid = 631
speed = 20
premium = false

[Doombringer]
id = 53
clientid = 644
speed = 20
premium = false

["Woodland Prince"]
id = 54
clientid = 647
speed = 20
premium = false

["Hailstorm Fury"]
id = 55
clientid = 648
speed = 20
premium = false

[Siegebreaker]
id = 56
clientid = 649
speed = 20
premium = false

[Poisonbane]
id = 57
clientid = 650
speed = 20
premium = false

[Blackpelt]
id = 58
clientid = 651
speed = 20
premium = false

["Golden Dragonfly"]
id = 59
clientid = 669
speed = 20
premium = false

["Steel Bee"]
id = 60
clientid = 670
speed = 20
premium = false

["Copper Fly"]
id = 61
clientid = 671
speed = 20
premium = false

["Tundra Rambler"]
id = 62
clientid = 672
speed = 20
premium = false

["Highland Yak"]
id = 63
clientid = 673
speed = 20
premium = false

["Glacier Vagabond"]
id = 64
clientid = 674
speed = 20
premium = false

["Flying Divan"]
id = 65
clientid = 688
speed = 20
premium = false

["Magic Carpet"]
id = 66
clientid = 689
speed = 20
premium = false

["Floating Kashmir"]
id = 67
clientid = 690
speed = 20
premium = false

["Ringtail Waccoon"]
id = 68
clientid = 691
speed = 20
premium = false

["Night Waccoon"]
id = 69
clientid = 692
speed = 20
premium = false

["Emerald Waccoon"]
id = 70
clientid = 693
speed = 20
premium = false

["Glooth Glider"]
id = 71
clientid = 682
speed = 20
premium = true

["Shadow Hart"]
id = 72
clientid = 685
speed = 20
premium = false

["Black Stag"]
id = 73
clientid = 686
speed = 20
premium = false

["Emperor Deer"]
id = 74
clientid = 687
speed = 20
premium = false

[Flitterkatzen]
id = 75
clientid = 726
speed = 20
premium = false

[Venompaw]
id = 76
clientid = 727
speed = 20
premium = false

[Batcat]
id = 77
clientid = 728
speed = 20
premium = false

["Sea Devil"]
id = 78
clientid = 734
speed = 20
premium = false

[Coralripper]
id = 79
clientid = 735
speed = 20
premium = false

[Plumfish]
id = 80
clientid = 736
speed = 20
premium = false

[Gorongra]
id = 81
clientid = 738
speed = 20
premium = false

[Noctungra]
id = 82
clientid = 739
speed = 20
premium = false

[Silverneck]
id = 83
clientid = 740
speed = 20
premium = false

[Slagsnare]
id = 84
clientid = 761
speed = 20
premium = false

[Nightstinger]
id = 85
clientid = 762
speed = 20
premium = false

[Razorcreep]
id = 86
clientid = 763
speed = 20
premium = false

["Rift Runner"]
id = 87
clientid = 848
speed = 20
premium = true

[Nightdweller]
id = 88
clientid = 849
speed = 20
premium = false

[Frostflare]
id = 89
clientid = 850
speed = 20
premium = false

[Cinderhoof]
id = 90
clientid = 851
speed = 20
premium = false

[Mouldpincer]
id = 91
clientid = 868
speed = 20
premium = false

[Bloodcurl]
id = 92
clientid = 869
speed = 20
premium = false

[Leafscuttler]
id = 93
clientid = 870
speed = 20
premium = false

[Sparkion]
id = 94
clientid = 883
speed = 20
premium = true

["Swamp Snapper"]
id = 95
clientid = 886
speed = 20
premium = false

["Mould Shell"]
id = 96
clientid = 887
speed = 20
premium = false

["Reed Lurker"]
id = 97
clientid = 888
speed = 20
premium = false

["Neon Sparkid"]
id = 98
clientid = 889
speed = 20
premium = true

[Vortexion]
id = 99
clientid = 890
speed = 20
premium = true

["Ivory Fang"]
id = 100
clientid = 901
speed = 20
premium = false

["Shadow Claw"]
id = 101
clientid = 902
speed = 20
premium = false

["Snow Pelt"]
id = 102
clientid = 903
speed = 20
premium = false
