// Copyright 2024 Black Tek Server Authors. All rights reserved.
// Use of this source code is governed by the GPL-2.0 License that can be found in the LICENSE file.

#ifndef FS_ITEMLOADER_H
#define FS_ITEMLOADER_H

enum itemgroup_t {
	ITEM_GROUP_NONE,

	ITEM_GROUP_GROUND,
	ITEM_GROUP_CONTAINER,
	ITEM_GROUP_WEAPON, //deprecated
	ITEM_GROUP_AMMUNITION, //deprecated
	ITEM_GROUP_ARMOR, //deprecated
	ITEM_GROUP_CHARGES,
	ITEM_GROUP_TELEPORT, //deprecated
	ITEM_GROUP_MAGICFIELD, //deprecated
	ITEM_GROUP_WRITEABLE, //deprecated
	ITEM_GROUP_KEY, //deprecated
	ITEM_GROUP_SPLASH,
	ITEM_GROUP_FLUID,
	ITEM_GROUP_DOOR, //deprecated
	ITEM_GROUP_DEPRECATED,
	ITEM_GROUP_PODIUM,

	ITEM_GROUP_LAST
};

enum ItemTypeDatAttribute : uint8_t {
    DAT_ATTR_GROUND = 0,
    DAT_ATTR_GROUND_BORDER = 1,
    DAT_ATTR_ON_BOTTOM = 2,
    DAT_ATTR_ON_TOP = 3,
    DAT_ATTR_CONTAINER = 4,
    DAT_ATTR_STACKABLE = 5,
    DAT_ATTR_FORCE_USE = 6,
    DAT_ATTR_MULTI_USE = 7,
    DAT_ATTR_WRITABLE = 8,
    DAT_ATTR_WRITABLE_ONCE = 9,
    DAT_ATTR_FLUID_CONTAINER = 10,
    DAT_ATTR_FLUID = 11,
    DAT_ATTR_UNPASSABLE = 12,
    DAT_ATTR_UNMOVEABLE = 13,
    DAT_ATTR_BLOCK_MISSILE = 14,
    DAT_ATTR_BLOCK_PATHFIND = 15,
    DAT_ATTR_NO_MOVE_ANIMATION = 16,
    DAT_ATTR_PICKUPABLE = 17,
    DAT_ATTR_HANGABLE = 18,
    DAT_ATTR_VERTICAL = 19,
    DAT_ATTR_HORIZONTAL = 20,
    DAT_ATTR_ROTATABLE = 21,
    DAT_ATTR_HAS_LIGHT = 22,
    DAT_ATTR_DONT_HIDE = 23,
    DAT_ATTR_TRANSLUCENT = 24,
    DAT_ATTR_HAS_OFFSET = 25,
    DAT_ATTR_HAS_ELEVATION = 26,
    DAT_ATTR_LYING_OBJECT = 27,
    DAT_ATTR_ANIMATE_ALWAYS = 28,
    DAT_ATTR_MINI_MAP = 29,
    DAT_ATTR_LENS_HELP = 30,
    DAT_ATTR_FULL_GROUND = 31,
    DAT_ATTR_IGNORE_LOOK = 32,
    DAT_ATTR_CLOTH = 33,
    DAT_ATTR_MARKET_ITEM = 34,
    DAT_ATTR_DEFAULT_ACTION = 35,
    DAT_ATTR_WRAPPABLE = 36,
    DAT_ATTR_UNWRAPPABLE = 37,
    DAT_ATTR_BOTTOM_EFFECT = 38,
    DAT_ATTR_USABLE = 254,
    DAT_ATTR_LAST_FLAG = 255
};

#endif
