name: Build - Docker

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    - "src/**"
  merge_group:
  push:
    paths:
    - "src/**"
    branches:
    - main

jobs:
  cancel-runs:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

  build_docker_arm:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: "5.x"

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Cache Docker layers
      uses: actions/cache@main
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-arm-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-arm-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3.2.0
      with:
        file: docker/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.gitversion.outputs.semVer }}
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, scope=${{ github.workflow }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Repository Registry Path
      run: echo ghcr.io/${{ github.repository }}:${{ steps.gitversion.outputs.semVer }}
